25 back routes
WildCodeSchool-2024-02/JS-lyon-0224-P3-cretchum pull request #26
Opened 2024-06-10 14:52 UTC by CharlotteR678

Added BREAD and route for user and home_structure tables
Added info in home_structure table so that it corresponds with the future home_structure inscription form

2024-06-10 15:09 UTC, Lith3 approved these changes

2024-06-11 07:21 UTC, YohanGH requested changes

2024-06-11 07:21 UTC, YohanGH commented on server/database/models/UsersRepository.js
> +      [
Error name :

 user.lastname,
         user.firstname,
         user.username,
         user.phone_number,
         user.location,
         user.mail,
         user.password,
         user.description,

2024-06-11 07:21 UTC, YohanGH commented on server/database/models/UsersRepository.js
> +      [
Pourquoi pas d'ID  dans le tableau des paramètres user alors que dans la lignes 36 on a [ID]

2024-06-11 09:15 UTC, Lith3 approved these changes

2024-06-11 09:53 UTC, YohanGH approved these changes
nothing to report

2024-06-11 12:43 UTC, merged