30 filter search page
WildCodeSchool-2024-02/JS-lyon-0224-P3-cretchum pull request #31
Opened 2024-06-12 15:01 UTC by YohanGH

2024-06-12 15:16 UTC, Lith3 approved these changes

2024-06-13 08:28 UTC, CharlotteR678 commented on client/src/pages/search-page/SearchPage.jsx
> +  useEffect(() => {
pourquoi useEffect et pas loader ?

2024-06-13 08:32 UTC, CharlotteR678 requested changes

2024-06-13 08:32 UTC, CharlotteR678 commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.animal && filters.animal !== "tous") {
il faut mettre "=== true" dans après filters.animal

2024-06-13 08:32 UTC, CharlotteR678 commented on client/src/pages/search-page/SearchPage.jsx
> +  useEffect(() => {
Pourquoi useEffect et pas le loader ?

2024-06-13 08:32 UTC, CharlotteR678 commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.structureType && filters.structureType !== "tous") {
pareil pour le "=== true"

2024-06-13 09:50 UTC, merged