Dev
WildCodeSchool-2024-02/JS-lyon-0224-P3-cretchum pull request #38
Opened 2024-06-13 14:03 UTC by CharlotteR678

US : 
27_link_signIn-form_to_bdd
26_connexion_page
30_functional_filter_search_page
25_back_routes
28_link_search-page_to_bdd
fix_sprint2

2024-06-13 14:08 UTC, YohanGH approved these changes
Nothing to report 😙

2024-06-13 14:22 UTC, Lith3 approved these changes

2024-06-13 14:26 UTC, wildmatthieu requested changes

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/main.jsx
> +              `http://localhost:3310/api/users/login`,
ne pas écrire en dur "http://localhost:3310", récupérer cette information depuis le .env dans le dossier client

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/main.jsx
> +                "Content-Type": "application/json",
ne pas écrire en dur "http://localhost:3310/", récupérer cette information depuis le .env dans le dossier client

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/main.jsx
> +            "http://localhost:3310/api/homestructure"
ne pas écrire en dur "http://localhost:3310/", récupérer cette information depuis le .env dans le dossier client

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.postalCode) {
explicitez les conditions : 
`filters.portalCode === ?`

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.animal && filters.animal !== "tous") {
explicitez les conditions : 
`filters.animal === ? && ...`

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.priceRange && filters.priceRange !== "tous") {
explicitez les conditions : 
`filters.priceRange === ?`

2024-06-13 14:26 UTC, wildmatthieu commented on client/src/pages/structure_form/StructureForm.jsx
le fichier commence à devenir pas mal long. C'est une questions "reflexion ouverte" : n'y aurait-il pas un moyen de redécouper ce fichier ? Ne vous embarquez pas forcemment la dessus pour ce sprint, réfléchissez y pour la suite

2024-06-13 14:26 UTC, wildmatthieu commented on server/app/services/ValidateLogin.js
> +  if (!error) {
explicitez les conditions : 
`!error === ?`

2024-06-13 14:26 UTC, wildmatthieu commented on server/app/services/validateSignIn.js
> +  if (!error) {
explicitez les conditions : 
`!error === ?`

2024-06-13 15:11 UTC, YohanGH commented on client/src/pages/search-page/SearchPage.jsx
> +      if (filters.priceRange && filters.priceRange !== "tous") {
✅

2024-06-14 07:33 UTC, wildmatthieu approved these changes

2024-06-14 07:33 UTC, merged