34_refactoring_db
WildCodeSchool-2024-02/JS-lyon-0224-P3-cretchum pull request #60
Opened 2024-06-20 14:18 UTC by CharlotteR678

BACK
Modifier la table Home_structure pour retirer ce qu'il y a en double avec la table users
Créer une table animal / race /  réservation
En profiter pour modifier les tables (CHAR(6) pour code_postale, changer le nom de la méthode .includes)
FRONT
Modifier le formulaire SignIn pour y ajouter un bouton (accueillir ou faire garder) - en profiter pour refaire le css (retirer les patounes) 
En profiter pour renommer SignIn en SignUp
Modifier le formulaire type="mail" => type="email"
Retirer le lien pour l'inscription des structures d'accueil dans HomePage (le lien se fait par les boutons ajoutés)
Ajouter les liens de redirections en fonction de la réponse dans main.jsx
Renommer le lien structure form par sa traduction française
En profiter  pour refaire le formulaire homeStructureForm

2024-06-20 14:54 UTC, YohanGH requested changes

2024-06-20 14:54 UTC, YohanGH commented on client/handlers/actions/structure_form_action/structureFormAction.js
> +        `http://localhost:3310/api/homestructure`,
Utilise le .env 👀

2024-06-20 15:02 UTC, YohanGH approved these changes

2024-06-20 17:55 UTC, Lith3 approved these changes

2024-06-24 12:23 UTC, HazeFury commented on server/database/schema.sql
> +  user_id INT(11) unsigned NOT NULL
il manque la FOREIGN KEY de la table race

2024-06-24 12:24 UTC, HazeFury commented on server/database/schema.sql
>  );
il manque les FOREIGN KEY de la table animal et home_structure

2024-06-24 12:42 UTC, HazeFury commented on server/database/schema.sql
> +  reservation_dates VARCHAR(255) NOT NULL,
allez pour chipoter un peu : pourquoi prendre 255 pour le varchar pour stocker une date de réservation ?? c'est un peu beaucoup nan ? 

C'est pas bloquant pour moi mais si vous pouvez arranger ça, ce serait cool ;)

2024-06-24 12:43 UTC, HazeFury requested changes
small things to change ^^

2024-06-24 13:04 UTC, HazeFury commented on server/database/models/HomeStructureRepository.js
> +      `update ${this.table} JOIN users ON ${this.table}.users_id = users.id set users.lastname = ?, users.firstname = ?, users.username =?, users.phone_number = ?, users.location = ?, users.mail = ?,
Vu avec Matthieu : 
la requête update est maxi longue et ce n'est pas une bonne pratique de toucher à deux table sur un seul model (Repository).


Pour remplacer ça, faite plutôt 2 appels séparés dans votre controller, le premier qui feras appel au model  de user et un autre appel au model de home_structure.

2024-06-24 13:28 UTC, wildmatthieu requested changes

2024-06-24 13:28 UTC, wildmatthieu commented on server/database/models/HomeStructureRepository.js
> +      `update ${this.table} set postal_code = ?,capacity = ?,is_professional = ?cat = ?, dog = ?, price =?  where id = ?`,
- ajouter une virgule entre ? et cat 
- vous etes sur que le code actuel fonctione tel que vous le souhaitez ?

2024-06-24 13:50 UTC, HazeFury approved these changes
ok 👍

2024-06-24 13:50 UTC, merged